version: '3'

services:
  ntp-front1:
    image: custom/chrony:local
    container_name: chrony-local1
    hostname: chrony.local1
    cap_add:
    - SYS_TIME
    env_file: .front.env
    networks:
      ntp_network:
        ipv4_address: 172.20.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  ntp-front2:
    image: custom/chrony:local
    container_name: chrony-local2
    hostname: chrony.local2
    env_file: .front.env
    cap_add:
    - SYS_TIME
    networks:
      ntp_network:
        ipv4_address: 172.20.0.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  ntp-front3:
    image: custom/chrony:local
    container_name: chrony-local3
    hostname: chrony.local3
    env_file: .front.env
    cap_add:
    - SYS_TIME
    networks:
      ntp_network:
        ipv4_address: 172.20.0.4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  ntp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/29

